import { Clone, useGLTF } from "@react-three/drei";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
export default function Model(props) {
//   const model = useGLTF("./books_with_magnifier_compressed.glb");
  const { nodes, materials } = useGLTF("/books_with_magnifier_compressed.glb");

  materials.Magnifier.depthWriter = true

  return (
    <>
      {/* <primitive object={model.scene} scale={props.scale} /> */}
      {/* 같은 geometry 와 material을 공유하는 메쉬를 여러개 사용할 때 (clone 으로 데이터 공유) */}
      {/* <Clone object={model.scene} scale={props.scale} position-x={-2} />
      <Clone object={model.scene} scale={props.scale} position-x={0} />
      <Clone object={model.scene} scale={props.scale} position-x={2} /> */}
      <group {...props} dispose={null}>
        <group scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Book_1_Book_1_Mat_0.geometry}
            material={materials.Book_1_Mat}
            position={[1.245, 2.425, 17.906]}
            rotation={[Math.PI, 1.426, 0]}
            scale={74.466}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Book_2_Book_2_Mat_0.geometry}
            material={materials.Book_2_Mat}
            position={[19.832, 0, 9.66]}
            rotation={[-Math.PI / 2, 0, -2.055]}
            scale={74.466}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Book_3_Book_3_Mat_0.geometry}
            material={materials.Book_3_Mat}
            position={[7.947, 6.977, 24.666]}
            rotation={[Math.PI, -1.164, 0]}
            scale={74.466}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Magnifier_Magnifier_0.geometry}
            material={materials.Magnifier}
            position={[-1.018, 3.294, -4.697]}
            rotation={[-1.58, 0.006, -0.544]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Open_book_Open_book_Mat_0.geometry}
            material={materials.Open_book_Mat}
            position={[0, 0, -4.723]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
          />
        </group>
      </group>
    </>
  );
}

useGLTF.preload("./books_with_magnifier_compressed.glb");
