/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Space(props) {
  const { nodes, materials } = useGLTF("./space.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.평면.geometry}
        material={nodes.평면.material}
        scale={[14.016, 8.417, 14.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus.geometry}
        material={nodes.Torus.material}
        position={[6.89, 0.231, 0.764]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus001.geometry}
        material={nodes.Torus001.material}
        position={[9.141, 0.172, 1.778]}
        scale={[0.774, 0.774, 0.784]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus002.geometry}
        material={nodes.Torus002.material}
        position={[6.869, 0.606, 0.761]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus003.geometry}
        material={nodes.Torus003.material}
        position={[6.869, 1.03, 0.761]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus004.geometry}
        material={nodes.Torus004.material}
        position={[6.869, 1.447, 0.761]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.실린더.geometry}
        material={nodes.실린더.material}
        position={[9.352, 1.211, -1.185]}
        scale={[0.232, 1.215, 0.237]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.원뿔.geometry}
        material={nodes.원뿔.material}
        position={[9.372, 3.409, -1.209]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.원뿔001.geometry}
        material={nodes.원뿔001.material}
        position={[6.519, 2.905, -3.901]}
        scale={[1.724, 1.628, 1.776]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.큐브.geometry}
        material={nodes.큐브.material}
        position={[6.537, 1.007, -3.895]}
        scale={0.873}
      />
    </group>
  );
}

useGLTF.preload("./space.glb");
